"""Initial DB structure

Revision ID: 008ef66ae845
Revises: 52dc17018616
Create Date: 2026-03-20 23:18:41.570012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '008ef66ae845'
down_revision: Union[str, Sequence[str], None] = '52dc17018616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listening_attempts', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('listening_attempts', sa.Column('passage', sa.Text(), nullable=False))
    op.add_column('listening_attempts', sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('listening_attempts', sa.Column('user_transcript', sa.Text(), nullable=False))
    op.add_column('listening_attempts', sa.Column('similarity_score', sa.Float(), nullable=False))
    op.add_column('listening_attempts', sa.Column('audio_filename', sa.String(), nullable=True))
    op.add_column('listening_attempts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_listening_attempts_id'), 'listening_attempts', ['id'], unique=False)
    op.add_column('pronunciation_results', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('pronunciation_results', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('pronunciation_results', sa.Column('reference_text', sa.String(), nullable=False))
    op.add_column('pronunciation_results', sa.Column('transcript', sa.String(), nullable=False))
    op.add_column('pronunciation_results', sa.Column('pronunciation_score', sa.Float(), nullable=False))
    op.add_column('pronunciation_results', sa.Column('total_mistakes', sa.Integer(), nullable=True))
    op.add_column('pronunciation_results', sa.Column('mistakes', sa.JSON(), nullable=True))
    op.add_column('pronunciation_results', sa.Column('improvement_tips', sa.JSON(), nullable=True))
    op.add_column('pronunciation_results', sa.Column('audio_path', sa.String(), nullable=True))
    op.add_column('pronunciation_results', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_pronunciation_results_id'), 'pronunciation_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pronunciation_results_id'), table_name='pronunciation_results')
    op.drop_column('pronunciation_results', 'created_at')
    op.drop_column('pronunciation_results', 'audio_path')
    op.drop_column('pronunciation_results', 'improvement_tips')
    op.drop_column('pronunciation_results', 'mistakes')
    op.drop_column('pronunciation_results', 'total_mistakes')
    op.drop_column('pronunciation_results', 'pronunciation_score')
    op.drop_column('pronunciation_results', 'transcript')
    op.drop_column('pronunciation_results', 'reference_text')
    op.drop_column('pronunciation_results', 'user_id')
    op.drop_column('pronunciation_results', 'id')
    op.drop_index(op.f('ix_listening_attempts_id'), table_name='listening_attempts')
    op.drop_column('listening_attempts', 'created_at')
    op.drop_column('listening_attempts', 'audio_filename')
    op.drop_column('listening_attempts', 'similarity_score')
    op.drop_column('listening_attempts', 'user_transcript')
    op.drop_column('listening_attempts', 'questions')
    op.drop_column('listening_attempts', 'passage')
    op.drop_column('listening_attempts', 'id')
    # ### end Alembic commands ###
