"""initial schema

Revision ID: 18fbf6989dbc
Revises: 
Create Date: 2026-04-06 18:26:14.960202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18fbf6989dbc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pronunciation_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_levels', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.String(length=20), nullable=False),
    sa.Column('completion_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weak_phonemes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_spent_mins', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_pronunciation_progress_user_id'), 'user_pronunciation_progress', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_pronunciation_progress_user_id'), table_name='user_pronunciation_progress')
    op.drop_table('user_pronunciation_progress')
    # ### end Alembic commands ###
