"""initial

Revision ID: 2e001eb99715
Revises: 
Create Date: 2026-04-05 09:28:19.267754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e001eb99715'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listening_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('passage', sa.Text(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_transcript', sa.Text(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('audio_filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listening_sessions_session_id'), 'listening_sessions', ['session_id'], unique=False)
    op.create_table('user_pronunciation_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_level', sa.String(length=20), nullable=False),
    sa.Column('overall_score_avg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('exercises_completed', sa.Integer(), nullable=False),
    sa.Column('time_spent_total_secs', sa.Integer(), nullable=False),
    sa.Column('weak_phonemes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strong_phonemes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('level_progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_practice_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_pronunciation_profile_user_id'), 'user_pronunciation_profile', ['user_id'], unique=True)
    op.create_table('phoneme_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phoneme', sa.String(length=50), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('correct_attempts', sa.Integer(), nullable=False),
    sa.Column('accuracy_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_pronunciation_profile.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'phoneme', name='uq_user_phoneme')
    )
    op.create_index(op.f('ix_phoneme_performance_user_id'), 'phoneme_performance', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phoneme_performance_user_id'), table_name='phoneme_performance')
    op.drop_table('phoneme_performance')
    op.drop_index(op.f('ix_user_pronunciation_profile_user_id'), table_name='user_pronunciation_profile')
    op.drop_table('user_pronunciation_profile')
    op.drop_index(op.f('ix_listening_sessions_session_id'), table_name='listening_sessions')
    op.drop_table('listening_sessions')
    # ### end Alembic commands ###
