"""fix_listening_session_nullable

Revision ID: 50c7bbff4ca9
Revises: e15e98421425
Create Date: 2026-04-05 16:57:39.286995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c7bbff4ca9'
down_revision: Union[str, Sequence[str], None] = 'e15e98421425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listening_sessions', 'user_transcript',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('listening_sessions', 'similarity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listening_sessions', 'similarity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('listening_sessions', 'user_transcript',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
