"""updated pronunciation model

Revision ID: 73784eba6ad7
Revises: 0f6df9ceaf40
Create Date: 2026-04-01 15:36:04.103146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73784eba6ad7'
down_revision: Union[str, Sequence[str], None] = '0f6df9ceaf40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phoneme_performance')
    op.drop_column('user_pronunciation_profile', 'level_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pronunciation_profile', sa.Column('level_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('phoneme_performance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phoneme', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('total_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correct_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accuracy_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('last_attempted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_pronunciation_profile.user_id'], name=op.f('phoneme_performance_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('phoneme_performance_pkey')),
    sa.UniqueConstraint('user_id', 'phoneme', name=op.f('uq_user_phoneme'))
    )
    # ### end Alembic commands ###
