"""fix primary key and add user_id

Revision ID: b62d9cb9c408
Revises: 1bacf9d06d6e
Create Date: 2026-03-22 14:51:42.279566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62d9cb9c408'
down_revision: Union[str, Sequence[str], None] = '1bacf9d06d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pronunciation_results', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('pronunciation_results', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pronunciation_results_id'), 'pronunciation_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pronunciation_results_id'), table_name='pronunciation_results')
    op.drop_column('pronunciation_results', 'user_id')
    op.drop_column('pronunciation_results', 'id')
    # ### end Alembic commands ###
