"""update_listening_session_mcq_cefr

Revision ID: ce53b713cf53
Revises: e02ddbdae9f0
Create Date: 2026-04-18 12:45:03.051017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce53b713cf53'
down_revision: Union[str, Sequence[str], None] = 'e02ddbdae9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listening_sessions', sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('listening_sessions', sa.Column('cefr_level', sa.String(length=8), nullable=True))
    op.add_column('listening_sessions', sa.Column('ability_score', sa.Float(), nullable=True))
    op.add_column('listening_sessions', sa.Column('accuracy_by_level', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('listening_sessions', sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('listening_sessions', 'questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_listening_sessions_session_id'), table_name='listening_sessions')
    op.create_index(op.f('ix_listening_sessions_session_id'), 'listening_sessions', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listening_sessions_session_id'), table_name='listening_sessions')
    op.create_index(op.f('ix_listening_sessions_session_id'), 'listening_sessions', ['session_id'], unique=False)
    op.alter_column('listening_sessions', 'questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('listening_sessions', 'evaluated_at')
    op.drop_column('listening_sessions', 'accuracy_by_level')
    op.drop_column('listening_sessions', 'ability_score')
    op.drop_column('listening_sessions', 'cefr_level')
    op.drop_column('listening_sessions', 'results')
    # ### end Alembic commands ###
