"""drop UserPronunciationProgress table

Revision ID: e02ddbdae9f0
Revises: 18fbf6989dbc
Create Date: 2026-04-06 19:03:27.613234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e02ddbdae9f0'
down_revision: Union[str, Sequence[str], None] = '18fbf6989dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_pronunciation_progress_user_id'), table_name='user_pronunciation_progress')
    op.drop_table('user_pronunciation_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pronunciation_progress',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('total_levels', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('completion_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('weak_phonemes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('time_spent_mins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pronunciation_progress_pkey'))
    )
    op.create_index(op.f('ix_user_pronunciation_progress_user_id'), 'user_pronunciation_progress', ['user_id'], unique=True)
    # ### end Alembic commands ###
