"""add_current_question

Revision ID: e15e98421425
Revises: 622f125290be
Create Date: 2026-04-05 15:54:44.599076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15e98421425'
down_revision: Union[str, Sequence[str], None] = '622f125290be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pronunciation_profile', sa.Column('current_question', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_pronunciation_profile', 'current_question')
    # ### end Alembic commands ###
