"""baseline

Revision ID: 0f6df9ceaf40
Revises: 
Create Date: 2026-04-01 15:11:40.387903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f6df9ceaf40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    


def downgrade() -> None:
   
    op.create_index(op.f('ix_listening_attempts_id'), 'listening_attempts', ['id'], unique=False)
    op.drop_table('users')
    # ### end Alembic commands ###
