
"""removed autogenerated uuid

Revision ID: 622f125290be
Revises: 4e29fde675c5
Create Date: 2026-04-05 10:23:28.870849
========
create phoneme_performance table

Revision ID: 5d3ea464050a
Revises: 8f7f946a9a59
Create Date: 2026-04-01 16:43:12.519520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.

revision: str = '622f125290be'
down_revision: Union[str, Sequence[str], None] = '4e29fde675c5'
========
revision: str = '5d3ea464050a'
down_revision: Union[str, Sequence[str], None] = '8f7f946a9a59'
260401164311.py
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
