"""removed autogenerated uuid

Revision ID: 622f125290be
Revises: 4e29fde675c5
Create Date: 2026-04-05 10:23:28.870849
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '622f125290be'
down_revision: Union[str, Sequence[str], None] = '4e29fde675c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    pass

def downgrade() -> None:
    pass